name: LoreCraft
main: net.bless.lc.LoreCraft
version: 0.0.1
author: Bless
description: When Crafting Item applys Chance to get Lore & Name Change on them this plugin is ment to be applyed with other plugins that apply lore stats